global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "users-service"
    static_configs:
      - targets: ["users:3000"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]