version: "3.9"
networks:
  monitoring:
    driver: bridge
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: projects 
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080