version: "3.9"
networks:
  monitoring:
    driver: bridge
services:
  # users: #docker run --rm -it -v ${PWD}:/work -w /work -p 5002:5000 aimvector/nodejs:1.0.0 /bin/sh
  #   container_name: users
  #   build:
  #     context: ./users
  #   ports:
  #     - 3001:3000
  #   networks:
  #     - monitoring
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: projects 
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080